# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-10-19T02:38:19Z"
  generation: 1
  labels:
    app: cesium-asdc
  name: cesium-asdc
  namespace: default
  resourceVersion: "5488"
  uid: f2fa4fc3-ce8b-45a0-a831-b9dd9a9a9203
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cesium-asdc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cesium-asdc
    spec:
      containers:
      - image: cesium_asdc
        imagePullPolicy: Never
        name: cesium-asdc-z4hxx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-10-19T02:38:19Z"
    lastUpdateTime: "2021-10-19T02:38:19Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-10-19T02:38:19Z"
    lastUpdateTime: "2021-10-19T02:38:19Z"
    message: ReplicaSet "cesium-asdc-5d9cd877b5" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
